"""added visibility column to Recipe

Revision ID: 138c256e9d46
Revises: 6d525152d592
Create Date: 2024-05-22 10:36:14.367898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138c256e9d46'
down_revision = '6d525152d592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
