"""added creator_photo_public_id column for Cloudinary api

Revision ID: 2ae1b52c6be9
Revises: 730209817410
Create Date: 2024-05-24 10:44:49.434942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae1b52c6be9'
down_revision = '730209817410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_photo_public_id', sa.String(), nullable=True))
        batch_op.drop_column('creator_photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_photo', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('creator_photo_public_id')

    # ### end Alembic commands ###
