"""removed family-only visibility

Revision ID: 4fa7522477e3
Revises: 2ae1b52c6be9
Create Date: 2024-07-11 11:56:49.935982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa7522477e3'
down_revision = '2ae1b52c6be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
