"""updated memory column in Recipe model

Revision ID: 641fdc0cca08
Revises: 3a71935a0df4
Create Date: 2024-05-22 14:36:27.038156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641fdc0cca08'
down_revision = '3a71935a0df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memory', sa.Text(), nullable=True))
        batch_op.drop_column('recipe_memory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_memory', sa.TEXT(), nullable=True))
        batch_op.drop_column('memory')

    # ### end Alembic commands ###
