"""optimizing models

Revision ID: 742271e910ae
Revises: bfb934a4b0e0
Create Date: 2024-07-11 13:51:34.891230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742271e910ae'
down_revision = 'bfb934a4b0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('creator_bio',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('creator_bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
