"""removed years from Recipe model

Revision ID: 9b1543fe9991
Revises: b976062218fd
Create Date: 2024-05-21 21:17:57.206707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1543fe9991'
down_revision = 'b976062218fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_name', sa.String(), nullable=True))
        batch_op.drop_column('creator_first_name')
        batch_op.drop_column('creator_death_year')
        batch_op.drop_column('creator_last_name')
        batch_op.drop_column('creator_birth_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_birth_year', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('creator_last_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('creator_death_year', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('creator_first_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('creator_name')

    # ### end Alembic commands ###
