"""fixed partially overlapping models

Revision ID: bfb934a4b0e0
Revises: 4fa7522477e3
Create Date: 2024-07-11 12:11:33.771888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb934a4b0e0'
down_revision = '4fa7522477e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('families')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('moderator_id', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_families'),
    sa.UniqueConstraint('name', name='uq_families_name')
    )
    # ### end Alembic commands ###
